
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000

logging:
  level:
    org:
      hibernate:
      #SQL: debug

decorator:
  datasource:
    p6spy:
      enable-logging: true


server:
  port: 8081
